"""Add maneuvers table

Revision ID: 77ffa2f38ffa
Revises: 82933601688b
Create Date: 2022-03-24 15:38:39.184699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ffa2f38ffa'
down_revision = '82933601688b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maneuver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('maneuver_type', sa.String(), nullable=True),
    sa.Column('dv_maneuver', sa.Float(), nullable=True),
    sa.Column('pos_man_x', sa.Float(), nullable=True),
    sa.Column('pos_man_y', sa.Float(), nullable=True),
    sa.Column('pos_man_z', sa.Float(), nullable=True),
    sa.Column('vel_man_x', sa.Float(), nullable=True),
    sa.Column('vel_man_y', sa.Float(), nullable=True),
    sa.Column('vel_man_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maneuver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maneuver_dv_maneuver'), ['dv_maneuver'], unique=False)

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index('ix_entry_dv_maneuver')
        batch_op.drop_column('pos_man_y')
        batch_op.drop_column('vel_man_y')
        batch_op.drop_column('pos_man_z')
        batch_op.drop_column('maneuver')
        batch_op.drop_column('dv_maneuver')
        batch_op.drop_column('vel_man_x')
        batch_op.drop_column('pos_man_x')
        batch_op.drop_column('vel_man_z')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vel_man_z', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pos_man_x', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vel_man_x', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dv_maneuver', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('maneuver', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pos_man_z', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vel_man_y', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pos_man_y', sa.FLOAT(), nullable=True))
        batch_op.create_index('ix_entry_dv_maneuver', ['dv_maneuver'], unique=False)

    with op.batch_alter_table('maneuver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maneuver_dv_maneuver'))

    op.drop_table('maneuver')
    # ### end Alembic commands ###
