"""Initial schema

Revision ID: db3508e20429
Revises: 
Create Date: 2022-03-14 16:36:23.821846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3508e20429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'architectures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sequence', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'bodies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('horizons_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'entries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bvec_theta', sa.Float(), nullable=False),
        sa.Column('bvec_abs', sa.Integer(), nullable=False),
        sa.Column('entry_trajec', sa.Boolean(), nullable=False),
        sa.Column('state_eq_rx', sa.Float(), nullable=True),
        sa.Column('state_eq_ry', sa.Float(), nullable=True),
        sa.Column('state_eq_rz', sa.Float(), nullable=True),
        sa.Column('state_eq_vx', sa.Float(), nullable=True),
        sa.Column('state_eq_vy', sa.Float(), nullable=True),
        sa.Column('state_eq_vz', sa.Float(), nullable=True),
        sa.Column('safe', sa.Boolean(), nullable=False),
        sa.Column('entry_state_rx', sa.Float(), nullable=False),
        sa.Column('entry_state_ry', sa.Float(), nullable=False),
        sa.Column('entry_state_rz', sa.Float(), nullable=False),
        sa.Column('entry_state_vx', sa.Float(), nullable=False),
        sa.Column('entry_state_vy', sa.Float(), nullable=False),
        sa.Column('entry_state_vz', sa.Float(), nullable=False),
        sa.Column('lon_entry', sa.Float(), nullable=True),
        sa.Column('lat_entry', sa.Float(), nullable=True),
        sa.Column('v_rot_x', sa.Float(), nullable=True),
        sa.Column('v_rot_y', sa.Float(), nullable=True),
        sa.Column('v_rot_z', sa.Float(), nullable=True),
        sa.Column('fpa', sa.Float(), nullable=True),
        sa.Column('v_rel_entry_x', sa.Float(), nullable=True),
        sa.Column('v_rel_entry_y', sa.Float(), nullable=True),
        sa.Column('v_rel_entry_z', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'flybys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('days', sa.Integer(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'trajectories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('launch_days', sa.Float(), nullable=True),
        sa.Column('arrive_days', sa.Float(), nullable=True),
        sa.Column('v_inf_x', sa.Float(), nullable=True),
        sa.Column('v_inf_y', sa.Float(), nullable=True),
        sa.Column('v_inf_z', sa.Float(), nullable=True),
        sa.Column('planet_pos_x', sa.Float(), nullable=True),
        sa.Column('planet_pos_y', sa.Float(), nullable=True),
        sa.Column('planet_pos_z', sa.Float(), nullable=True),
        sa.Column('planet_vel_x', sa.Float(), nullable=True),
        sa.Column('planet_vel_y', sa.Float(), nullable=True),
        sa.Column('planet_vel_z', sa.Float(), nullable=True),
        sa.Column('c3', sa.Float(), nullable=True),
        sa.Column('delta_v', sa.Float(), nullable=True),
        sa.Column('arrival_mass', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trajectories')
    op.drop_table('flybys')
    op.drop_table('entries')
    op.drop_table('bodies')
    op.drop_table('architectures')
    # ### end Alembic commands ###
